// Mock user accounts
const MOCK_USERS = [
  {
    id: 'u1',
    username: 'SafetyAdmin',
    password: 'admin123',
    role: 'admin',
    displayName: 'Safety Admin',
    bio: 'UKSA founding admin. Here to keep the community safe.',
    email: 'admin@uksafetyalerts.org',
    fetlife: 'https://fetlife.com/users/SafetyAdmin',
    discord: { username: 'SafetyAdmin', id: '123456789012345678', linked: true },
    joinedDate: '2024-03-01',
  },
  {
    id: 'u2',
    username: 'ModeratorJane',
    password: 'mod123',
    role: 'moderator',
    displayName: 'Jane M.',
    bio: 'Moderator covering London and South East.',
    email: 'jane@uksafetyalerts.org',
    fetlife: 'https://fetlife.com/users/JaneMod',
    discord: { username: 'JaneMod', id: '234567890123456789', linked: true },
    joinedDate: '2024-05-12',
  },
  {
    id: 'u3',
    username: 'ModeratorTom',
    password: 'mod456',
    role: 'moderator',
    displayName: 'Tom',
    bio: 'Northern England moderator.',
    email: 'tom@uksafetyalerts.org',
    fetlife: null,
    discord: { username: 'TomMod', id: '345678901234567890', linked: true },
    joinedDate: '2024-07-20',
  },
  {
    id: 'u4',
    username: 'MemberAlex',
    password: 'user123',
    role: 'user',
    displayName: 'Alex',
    bio: '',
    email: 'alex@example.com',
    fetlife: 'https://fetlife.com/users/AlexMember',
    discord: null,
    joinedDate: '2025-01-08',
  },
  {
    id: 'u5',
    username: 'MemberSarah',
    password: 'user456',
    role: 'user',
    displayName: 'Sarah S.',
    bio: 'Community member, Bristol area.',
    email: null,
    fetlife: null,
    discord: { username: 'Sarah_S', id: '456789012345678901', linked: true },
    joinedDate: '2025-03-15',
  },
];

// Areas of activity options — all UK counties
const AREAS = [
  // England
  'Bedfordshire', 'Berkshire', 'Bristol', 'Buckinghamshire', 'Cambridgeshire',
  'Cheshire', 'Cornwall', 'Cumbria', 'Derbyshire', 'Devon', 'Dorset',
  'Durham', 'East Riding of Yorkshire', 'East Sussex', 'Essex',
  'Gloucestershire', 'Greater London', 'Greater Manchester', 'Hampshire',
  'Herefordshire', 'Hertfordshire', 'Isle of Wight', 'Kent', 'Lancashire',
  'Leicestershire', 'Lincolnshire', 'Merseyside', 'Norfolk',
  'North Yorkshire', 'Northamptonshire', 'Northumberland', 'Nottinghamshire',
  'Oxfordshire', 'Rutland', 'Shropshire', 'Somerset', 'South Yorkshire',
  'Staffordshire', 'Suffolk', 'Surrey', 'Tyne and Wear', 'Warwickshire',
  'West Midlands', 'West Sussex', 'West Yorkshire', 'Wiltshire', 'Worcestershire',
  // Wales
  'Blaenau Gwent', 'Bridgend', 'Caerphilly', 'Cardiff', 'Carmarthenshire',
  'Ceredigion', 'Conwy', 'Denbighshire', 'Flintshire', 'Gwynedd',
  'Isle of Anglesey', 'Merthyr Tydfil', 'Monmouthshire', 'Neath Port Talbot',
  'Newport', 'Pembrokeshire', 'Powys', 'Rhondda Cynon Taf', 'Swansea',
  'Torfaen', 'Vale of Glamorgan', 'Wrexham',
  // Scotland
  'Aberdeen City', 'Aberdeenshire', 'Angus', 'Argyll and Bute',
  'City of Edinburgh', 'Clackmannanshire', 'Dumfries and Galloway',
  'Dundee City', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian',
  'East Renfrewshire', 'Falkirk', 'Fife', 'Glasgow City', 'Highland',
  'Inverclyde', 'Midlothian', 'Moray', 'Na h-Eileanan Siar', 'North Ayrshire',
  'North Lanarkshire', 'Orkney Islands', 'Perth and Kinross', 'Renfrewshire',
  'Scottish Borders', 'Shetland Islands', 'South Ayrshire', 'South Lanarkshire',
  'Stirling', 'West Dunbartonshire', 'West Lothian',
  // Northern Ireland
  'Antrim and Newtownabbey', 'Ards and North Down',
  'Armagh City, Banbridge and Craigavon', 'Belfast',
  'Causeway Coast and Glens', 'Derry City and Strabane',
  'Fermanagh and Omagh', 'Lisburn and Castlereagh',
  'Mid and East Antrim', 'Mid Ulster', 'Newry, Mourne and Down',
];

// Names of Concern entries
const MOCK_ENTRIES = [
  {
    id: 'e1',
    handle: 'DarkMaster99',
    aliases: ['DM99', 'TheDarkOne'],
    areas: ['Greater London', 'Surrey'],
    description: 'Multiple reports of ignoring safe words and consent violations at events.',
    severity: 'high',
    listedBy: 'u1',
    dateAdded: '2025-11-03',
    dateUpdated: '2026-01-15',
    status: 'active',
  },
  {
    id: 'e2',
    handle: 'VenusRising',
    aliases: [],
    areas: ['Greater Manchester', 'West Midlands'],
    description: 'Known to misrepresent identity and experience level to new members.',
    severity: 'medium',
    listedBy: 'u2',
    dateAdded: '2025-12-08',
    dateUpdated: '2025-12-08',
    status: 'active',
  },
  {
    id: 'e3',
    handle: 'SilentShadow',
    aliases: ['SS_UK', 'ShadowMaster'],
    areas: ['Online / Nationwide'],
    description: 'Repeatedly shares non-consensual imagery in private chats. Multiple reports from different servers.',
    severity: 'high',
    listedBy: 'u2',
    dateAdded: '2026-01-20',
    dateUpdated: '2026-02-14',
    status: 'active',
  },
  {
    id: 'e4',
    handle: 'KinksterKev',
    aliases: ['KevKink'],
    areas: ['Bristol', 'Somerset'],
    description: 'Photographed attendees without consent at multiple events.',
    severity: 'medium',
    listedBy: 'u3',
    dateAdded: '2026-02-01',
    dateUpdated: '2026-02-01',
    status: 'active',
  },
  {
    id: 'e5',
    handle: 'PhoenixRising_UK',
    aliases: [],
    areas: ['Online / Nationwide'],
    description: 'Harassment and stalking behaviour reported by three separate individuals. Continues to create new accounts after bans.',
    severity: 'high',
    listedBy: 'u1',
    dateAdded: '2026-03-10',
    dateUpdated: '2026-04-02',
    status: 'active',
  },
  {
    id: 'e6',
    handle: 'TwilightDom',
    aliases: ['TwilightD'],
    areas: ['City of Edinburgh', 'Midlothian'],
    description: 'Reports of unsafe rope work after falsely claiming certification.',
    severity: 'medium',
    listedBy: 'u2',
    dateAdded: '2026-03-22',
    dateUpdated: '2026-03-22',
    status: 'active',
  },
  {
    id: 'e7',
    handle: 'NightOwl_Kink',
    aliases: ['NO_Kink', 'NightOwlUK'],
    areas: ['Online / Nationwide'],
    description: 'Distributes unsolicited explicit content. Targets newcomers.',
    severity: 'low',
    listedBy: 'u3',
    dateAdded: '2026-04-05',
    dateUpdated: '2026-04-05',
    status: 'active',
  },
  {
    id: 'e8',
    handle: 'LordOfChains',
    aliases: [],
    areas: ['Greater London', 'West Midlands'],
    description: 'Under review following recent reports. Investigation ongoing.',
    severity: 'low',
    listedBy: 'u1',
    dateAdded: '2026-05-18',
    dateUpdated: '2026-06-01',
    status: 'under_review',
  },
  {
    id: 'e9',
    handle: 'CrimsonRose',
    aliases: ['RoseCrimson', 'CR_UK'],
    areas: ['West Yorkshire', 'South Yorkshire'],
    description: 'Grooming behaviour reported. Targets individuals new to the community.',
    severity: 'high',
    listedBy: 'u2',
    dateAdded: '2026-05-30',
    dateUpdated: '2026-06-10',
    status: 'active',
  },
  {
    id: 'e10',
    handle: 'IronWolf88',
    aliases: [],
    areas: ['Online / Nationwide'],
    description: 'Previous listing resolved after mediation. Kept for record purposes.',
    severity: 'low',
    listedBy: 'u3',
    dateAdded: '2025-09-14',
    dateUpdated: '2026-01-08',
    status: 'resolved',
  },
];
