// Mock user accounts
const MOCK_USERS = [
  {
    id: 'u1',
    username: 'SafetyAdmin',
    password: 'admin123',
    role: 'admin',
    email: 'admin@uksafetyalerts.org',
    fetlife: 'https://fetlife.com/users/SafetyAdmin',
    discord: 'SafetyAdmin#0001',
  },
  {
    id: 'u2',
    username: 'ModeratorJane',
    password: 'mod123',
    role: 'moderator',
    email: 'jane@uksafetyalerts.org',
    fetlife: 'https://fetlife.com/users/JaneMod',
    discord: 'JaneMod#4521',
  },
  {
    id: 'u3',
    username: 'ModeratorTom',
    password: 'mod456',
    role: 'moderator',
    email: 'tom@uksafetyalerts.org',
    fetlife: null,
    discord: 'TomMod#8812',
  },
  {
    id: 'u4',
    username: 'MemberAlex',
    password: 'user123',
    role: 'user',
    email: 'alex@example.com',
    fetlife: 'https://fetlife.com/users/AlexMember',
    discord: 'AlexMember#3344',
  },
  {
    id: 'u5',
    username: 'MemberSarah',
    password: 'user456',
    role: 'user',
    email: 'sarah@example.com',
    fetlife: null,
    discord: 'Sarah_S#7799',
  },
];

// Areas of activity options
const AREAS = [
  'FetLife', 'Discord', 'Telegram', 'Reddit', 'Facebook', 'Instagram',
  'Twitter/X', 'Fetish Events (London)', 'Fetish Events (Manchester)',
  'Fetish Events (Birmingham)', 'Fetish Events (Edinburgh)',
  'Fetish Events (Bristol)', 'Online Communities', 'Local Munches',
];

// Names of Concern entries
const MOCK_ENTRIES = [
  {
    id: 'e1',
    handle: 'DarkMaster99',
    aliases: ['DM99', 'TheDarkOne'],
    areas: ['FetLife', 'Discord', 'Fetish Events (London)'],
    description: 'Multiple reports of ignoring safe words and consent violations at events.',
    severity: 'high',
    listedBy: 'u1',
    dateAdded: '2025-11-03',
    dateUpdated: '2026-01-15',
    status: 'active',
  },
  {
    id: 'e2',
    handle: 'VenusRising',
    aliases: [],
    areas: ['FetLife', 'Fetish Events (Manchester)', 'Fetish Events (Birmingham)'],
    description: 'Known to misrepresent identity and experience level to new members.',
    severity: 'medium',
    listedBy: 'u2',
    dateAdded: '2025-12-08',
    dateUpdated: '2025-12-08',
    status: 'active',
  },
  {
    id: 'e3',
    handle: 'SilentShadow',
    aliases: ['SS_UK', 'ShadowMaster'],
    areas: ['Discord', 'Telegram', 'Reddit'],
    description: 'Repeatedly shares non-consensual imagery in private chats. Multiple reports from different servers.',
    severity: 'high',
    listedBy: 'u2',
    dateAdded: '2026-01-20',
    dateUpdated: '2026-02-14',
    status: 'active',
  },
  {
    id: 'e4',
    handle: 'KinksterKev',
    aliases: ['KevKink'],
    areas: ['FetLife', 'Local Munches', 'Fetish Events (Bristol)'],
    description: 'Photographed attendees without consent at multiple events.',
    severity: 'medium',
    listedBy: 'u3',
    dateAdded: '2026-02-01',
    dateUpdated: '2026-02-01',
    status: 'active',
  },
  {
    id: 'e5',
    handle: 'PhoenixRising_UK',
    aliases: [],
    areas: ['Discord', 'Online Communities'],
    description: 'Harassment and stalking behaviour reported by three separate individuals. Continues to create new accounts after bans.',
    severity: 'high',
    listedBy: 'u1',
    dateAdded: '2026-03-10',
    dateUpdated: '2026-04-02',
    status: 'active',
  },
  {
    id: 'e6',
    handle: 'TwilightDom',
    aliases: ['TwilightD'],
    areas: ['FetLife', 'Fetish Events (Edinburgh)'],
    description: 'Reports of unsafe rope work after falsely claiming certification.',
    severity: 'medium',
    listedBy: 'u2',
    dateAdded: '2026-03-22',
    dateUpdated: '2026-03-22',
    status: 'active',
  },
  {
    id: 'e7',
    handle: 'NightOwl_Kink',
    aliases: ['NO_Kink', 'NightOwlUK'],
    areas: ['Reddit', 'Discord', 'Telegram'],
    description: 'Distributes unsolicited explicit content. Targets newcomers.',
    severity: 'low',
    listedBy: 'u3',
    dateAdded: '2026-04-05',
    dateUpdated: '2026-04-05',
    status: 'active',
  },
  {
    id: 'e8',
    handle: 'LordOfChains',
    aliases: [],
    areas: ['FetLife', 'Fetish Events (London)', 'Fetish Events (Birmingham)'],
    description: 'Under review following recent reports. Investigation ongoing.',
    severity: 'low',
    listedBy: 'u1',
    dateAdded: '2026-05-18',
    dateUpdated: '2026-06-01',
    status: 'under_review',
  },
  {
    id: 'e9',
    handle: 'CrimsonRose',
    aliases: ['RoseCrimson', 'CR_UK'],
    areas: ['Facebook', 'Instagram', 'Local Munches'],
    description: 'Grooming behaviour reported. Targets individuals new to the community.',
    severity: 'high',
    listedBy: 'u2',
    dateAdded: '2026-05-30',
    dateUpdated: '2026-06-10',
    status: 'active',
  },
  {
    id: 'e10',
    handle: 'IronWolf88',
    aliases: [],
    areas: ['Discord'],
    description: 'Previous listing resolved after mediation. Kept for record purposes.',
    severity: 'low',
    listedBy: 'u3',
    dateAdded: '2025-09-14',
    dateUpdated: '2026-01-08',
    status: 'resolved',
  },
];
